### ISSUE TITLE
Build for LightInject 4.1.4

### ISSUE THREAD

**Issue by pavlalexandr** [seesharper/LightInject.AutoFactory#3]
I getting the next exception during ServiceContainer.EnableAutoFactories() method execution: 
"An exception of type 'System.MissingMethodException' occurred in <.dll> but was not handled in user code

Additional information: Method not found: "Void LightInject.IServiceRegistry.RegisterConstructorDependency(System.Func`3<LightInject.IServiceFactory,System.Reflection.ParameterInfo,!!0>)".
"

The code I use:
`var container = new ServiceContainer();
            container.RegisterFrom<WebApiCompositionRoot>();
            container.EnableAutoFactories();
            container.RegisterAutoFactory<IValidatorFactory>();          
            container.EnablePerWebRequestScope();
`

The versions of the packages:
`
<package id="LightInject" version="4.1.0" targetFramework="net452" />
  <package id="LightInject.AutoFactory" version="1.0.0.1" targetFramework="net452" />
  <package id="LightInject.Web" version="1.0.0.3" targetFramework="net452" />
  <package id="LightInject.WebApi" version="1.1.0" targetFramework="net452" />
`

When I downgrade the Lightinject.dll version then everything is fine, so I think the problem in that version.

**Comment by kreediam** [comment]
Hi Bernard, I'm running into this issue as well. Are there plans to publish 1.1.1 to nuget.org?
